# 📊 Module 2: Exploratory Data Analysis (EDA) & Data Wrangling

**Weeks 4–6 | Beginner Data Science Program**

---

## Welcome!

This is the module where Python transforms from a **programming language** into a **data tool**.

You'll work with real-world-style datasets — messy, incomplete, and full of surprises. The goal is to build **data instincts**: before any analysis or modeling, a data scientist must understand the shape, quality, and quirks of their data.

> 💡 **Key Mindset:** EDA is not a checklist — it is an **investigative mindset**.

---

## 📋 What You'll Learn

| Week | Topics |
|------|--------|
| **Week 4** | NumPy foundations, Arrays, Pandas Series & DataFrames, Loading data |
| **Week 5** | Selecting, filtering, cleaning, string & datetime operations |
| **Week 6** | Grouping, aggregating, reshaping, merging DataFrames |

---

## ✅ By the end of this module you will be able to:

1. Load data from CSV, Excel, and JSON files into a Pandas DataFrame
2. Immediately assess a new dataset's shape, types, missing values, and statistics
3. Select rows and columns using `.loc` and `.iloc` indexing
4. Filter DataFrames using complex boolean conditions
5. Handle missing data strategically
6. Create, rename, drop, and reorder columns
7. Apply string and datetime operations using `.str` and `.dt` accessors
8. Group, aggregate, and summarize data using `groupby()`
9. Reshape data using `pivot_table()`, `melt()`, and `stack()`
10. Perform vectorized operations with NumPy
11. Combine multiple DataFrames using `merge()`, `join()`, and `concat()`

---
# 📦 WEEK 4: NumPy Foundations & DataFrame Basics
---

## 4.1 — Why NumPy Exists

Python lists are flexible — they can hold any mix of data types. But that flexibility comes at a **performance cost**.

When doing numerical computation (math on thousands or millions of numbers), Python lists are **slow**. NumPy solves this with arrays that:
- Store only **one data type** (homogeneous)
- Are stored in **contiguous memory** (fast access)
- Support **vectorized operations** (no Python loops needed)

```
Python list: [1, 'hello', 3.14, True]  ← any type, flexible, slow for math
NumPy array: [1, 2, 3, 4, 5]           ← one type, fast, vectorized
```

In [1]:
# Always import NumPy as 'np' — this is the universal convention
import numpy as np

# Quick performance demo: adding 1 to every element
python_list = list(range(1_000_000))
numpy_array = np.arange(1_000_000)

# Python list approach (slow — uses a loop)
%timeit [x + 1 for x in python_list]

# NumPy approach (fast — vectorized, no loop)
%timeit numpy_array + 1

198 ms ± 20.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
7.28 ms ± 1.36 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

## 4.2 — Creating NumPy Arrays

There are many ways to create arrays. Here are the most important ones:

In [7]:
# From a Python list
arr1 = np.array([10, 20, 30, 40, 50])
print("From list:", arr1)
print(type(arr1))

From list: [10 20 30 40 50]
<class 'numpy.ndarray'>

In [11]:
ones = np.ones(5)
print(ones)
print(type(ones))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>

In [13]:
full = np.full((2,3), 7)
print(full)

[[7 7 7]
 [7 7 7]]

In [14]:
arange = np.arange(0, 20, 5)
print(arange)

[ 0  5 10 15]

In [18]:
linespace = np.linspace(0, 20, 5)
print(linespace)

[ 0.  5. 10. 15. 20.]

In [19]:
# Filled with zeros or ones
zeros = np.zeros(5)          # [0. 0. 0. 0. 0.]
ones  = np.ones((2, 3))      # 2x3 matrix of 1s
full  = np.full((2, 3), 7)   # 2x3 matrix filled with 7
print("\nZeros:", zeros)
print("\nOnes (2x3):\n", ones)
print("\nFull of 7s (2x3):\n", full)

# Sequences
arange  = np.arange(0, 20, 5)        # [0, 5, 10, 15]  — like range() but returns array
linspace = np.linspace(0, 1, 5)      # [0, 0.25, 0.5, 0.75, 1.0]  — evenly spaced INCLUDING endpoint
print("\narange(0,20,5):", arange)
print("linspace(0,1,5):", linspace)

Zeros: [0. 0. 0. 0. 0.]

Ones (2x3):
 [[1. 1. 1.]
 [1. 1. 1.]]

Full of 7s (2x3):
 [[7 7 7]
 [7 7 7]]

arange(0,20,5): [ 0  5 10 15]
linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]

In [21]:
# ⚠️ IMPORTANT: Always set a random seed for reproducibility!
# This ensures you get the same 'random' numbers every time you run the code.
np.random.seed(42)

rand_uniform = np.random.rand(3, 3)         # Uniform distribution [0, 1)
rand_normal  = np.random.randn(3, 3)        # Standard normal (mean=0, std=1)
rand_ints    = np.random.randint(1, 100, 10) # 10 integers between 1 and 99

print("Random uniform (3x3):\n", rand_uniform)
print("\nRandom integers (10):", rand_ints)
print(rand_normal)

Random uniform (3x3):
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]

Random integers (10): [80 15 62 62 47 62 51 55 64  3]
[[-0.58087813 -0.52516981 -0.57138017]
 [-0.92408284 -2.61254901  0.95036968]
 [ 0.81644508 -1.523876   -0.42804606]]

## 4.3 — Array Properties & Reshaping

Every NumPy array has attributes that describe its structure.

In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])    

arr.shape
print(arr.ndim)
print(arr.size)
print(arr.dtype)

2
6
int64

In [29]:
flat = np.arange(12)
print(flat)
print(flat.ndim)

reshaped = flat.reshape(3, 4)
print(reshaped)
print(reshaped.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  # ---> 2 steps to access an element eg. 1  



arr_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  # 3 steps to access an element eg. 1
print(arr_3)
print(arr_3.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3

In [32]:
print(reshaped)

print("=======================================")

transposed  = reshaped.T  #swapping rows with columns --- rows become columns and vice versa
print(transposed)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
=======================================
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

In [34]:
print(reshaped)

print("=======================================")

original  = reshaped.flatten()
print(original)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
=======================================
[ 0  1  2  3  4  5  6  7  8  9 10 11]

In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)   # (2, 3) — 2 rows, 3 columns
print("Dimensions:", arr.ndim)  # 2 — it's a 2D array
print("Total elements:", arr.size)  # 6
print("Data type:", arr.dtype)      # int64

# Reshaping — the total number of elements must stay the same!
flat = np.arange(12)           # [0, 1, 2, ..., 11]
reshaped = flat.reshape(3, 4)  # 3 rows x 4 cols = 12 elements ✓
print("\nOriginal (12,):", flat)
print("\nReshaped (3,4):\n", reshaped)

# Transposing — swap rows and columns
print("\nTransposed (4,3):\n", reshaped.T)

# Flattening back to 1D
# .flatten() returns a COPY (safe to modify)
# .ravel()   returns a VIEW when possible (faster but be careful)
print("\nFlattened:", reshaped.flatten())

Shape: (2, 3)
Dimensions: 2
Total elements: 6
Data type: int64

Original (12,): [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped (3,4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Transposed (4,3):
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]

In [38]:
# Type casting   --- converting to a diffrent datatype
float_arr = np.array([1.7, 2.9, 3.1])
int_arr   = float_arr.astype(int)   # Truncates decimals — does NOT round!
print("Float:", float_arr)
print("Cast to int:", int_arr)  # [1, 2, 3]  ← NOT [2, 3, 3]

Float: [1.7 2.9 3.1]
Cast to int: [1 2 3]

## 4.4 — Vectorized Operations & Broadcasting

The superpower of NumPy: **apply operations to entire arrays without writing loops**.

In [40]:
a = np.array([10, 20, 30, 40, 50])  #first array
b = np.array([1,   2,  3,  4,  5])  #second one

print( a + b)

[11 22 33 44 55]

In [43]:
a = np.array([10, 20, 30, 40, 50])  #first array
b = np.array([1,   2,  3,  4,  5])

print("a + b =", a + b)     # Element-wise addition
print("a * b =", a * b)     # Element-wise multiplication
print("a ** 2 =", a ** 2)   # Element-wise squaring
print("a / 10 =", a / 10)   # Scalar broadcast — divides EVERY element by 10

# Universal functions (ufuncs)
print("\nsqrt(a):", np.sqrt(a))
print("log(a): ", np.log(a))
print("abs([-1,-2,3]):", np.abs(np.array([-1, -2, 3])))  #absolute number

a + b = [11 22 33 44 55]
a * b = [ 10  40  90 160 250]
a ** 2 = [ 100  400  900 1600 2500]
a / 10 = [1. 2. 3. 4. 5.]

sqrt(a): [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
log(a):  [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
abs([-1,-2,3]): [1 2 3]

In [45]:
# Aggregation functions
data = np.array([[4, 7, 2],
                 [1, 8, 5]])

print("Sum of all elements:", np.sum(data))
print("-------------------------------------------")

print("Column Sums: ", np.sum(data, axis=0) )

print("Row Sums: ", np.sum(data, axis=1))

Sum of all elements: 27
-------------------------------------------
Column Sums:  [ 5 15  7]
Row Sums:  [13 14]

In [46]:
# Aggregation functions
data = np.array([[4, 7, 2],
                 [1, 8, 5]])

print("Sum of all elements:", np.sum(data))
print("Mean of all elements:", np.mean(data))
print("Max of all elements:", np.max(data))

# The axis parameter is crucial!
# axis=0: operate DOWN the rows → result has one value per COLUMN
# axis=1: operate ACROSS columns → result has one value per ROW
print("\nColumn sums (axis=0):", np.sum(data, axis=0))  # [5, 15, 7]
print("Row sums   (axis=1):", np.sum(data, axis=1))     # [13, 14]

# Cumulative operations
arr = np.array([1, 2, 3, 4, 5])
print("\nCumulative sum:", np.cumsum(arr))  # [1, 3, 6, 10, 15]

Sum of all elements: 27
Mean of all elements: 4.5
Max of all elements: 8

Column sums (axis=0): [ 5 15  7]
Row sums   (axis=1): [13 14]

Cumulative sum: [ 1  3  6 10 15]

## 4.5 — Boolean Masking with NumPy

Comparing an array to a value creates a **boolean array** — a mask of True/False values. You can use this mask to **filter** the array.

Data - column os salaries; and we want to filter the data by employees whose salaraies are below 20000 --- when we create a filter of this , that's called masking 
  
#########################

employee_1  == True, 

employee_3 = False

In [ ]:
scores = np.array([45, 82, 61, 90, 55, 78, 33, 95])

# passed , should have a score greater than or equal to 60
passed = scores >= 60    # boolean mask 
print(passed)

print("########################################")

#use the boolean mask to filter scores
students_passed = scores[passed]
print(students_passed)




# 1. YOu have to have a condition ---- For a student to pass he/she has to have a score greater that or equalt to 60
# 2. Create a boolean mask ---- passed = scores >= 60
# 3. Use mask to filter the data --- student_passed = scores[passed]

[False  True  True  True False  True False  True]
########################################
[82 61 90 78 95]

In [ ]:
scores = np.array([45, 82, 61, 90, 55, 78, 33, 95])

# Create a boolean mask
passed = scores >= 60
print("Scores:", scores)
print("Passed?:", passed)           # [False True True True False True False True]
print("Passing scores:", scores[passed])  # Uses mask to filter — [82 61 90 78 95]

# Combining conditions — MUST use & (AND) and | (OR), not Python's 'and'/'or'!
distinction = (scores >= 75) | (scores <= 100)
print("\nDistinction scores:", scores[distinction])

# np.where: vectorized if/else
# np.where(condition, value_if_true, value_if_false)
grade = np.where(scores >= 60, "Pass", "Fail")
print("\nGrades:", grade)

# Find the index of max/min
print("\nIndex of highest score:", np.argmax(scores), "→ score:", scores[np.argmax(scores)])
print("Index of lowest score: ", np.argmin(scores), "→ score:", scores[np.argmin(scores)])

## 4.6 — Introducing Pandas

NumPy is powerful but has limitations — it can't easily handle:
- **Mixed data types** in a table (numbers AND strings)
- **Named columns and rows** (labels)
- **Built-in data analysis** operations

**Pandas** is built on top of NumPy and solves all of these. It's the #1 data analysis library in Python.

```
NumPy → fast numerical arrays
Pandas → labeled tables with mixed types + analysis tools
```

Pandas has two core data structures:
- **Series** — a 1D labeled array (like a single spreadsheet column)
- **DataFrame** — a 2D labeled table (like a full spreadsheet)

In [2]:
import pandas as pd  # 'pd' is the universal convention   

import numpy as np 

print("Pandas version:", pd.__version__)
print("NumPy version: ", np.__version__)

Pandas version: 3.0.3
NumPy version:  2.4.6

## 4.7 — Series: The Building Block

In [ ]:
arr = np.array([22, 25, 19, 30, 28])

data = pd.Series([22, 25, 19, 30, 28], index=['Mon', 'Tue', 'Wed', 'Thu', 'Fri']) 

print(type(arr))
print(arr)
print("====================================")

print(type(data))
print(data)

<class 'numpy.ndarray'>
[22 25 19 30 28]
====================================
<class 'pandas.Series'>
Mon    22
Tue    25
Wed    19
Thu    30
Fri    28
dtype: int64

In [5]:
stock = pd.Series({'AAPL': 150.2, 'GOOG': 2800.5, 'MSFT': 299.0})
print(stock)

AAPL     150.2
GOOG    2800.5
MSFT     299.0
dtype: float64

In [6]:
# Creating a Series from a list (default integer index)
temps = pd.Series([22, 25, 19, 30, 28])
print("Series from list:")
print(temps)

# Creating with a custom index (labels)
temps_labelled = pd.Series([22, 25, 19, 30, 28],
                            index=['Mon', 'Tue', 'Wed', 'Thu', 'Fri'])
print("\nSeries with labels:")
print(temps_labelled)

# Creating from a dictionary (keys become the index)
stock = pd.Series({'AAPL': 150.2, 'GOOG': 2800.5, 'MSFT': 299.0})
print("\nSeries from dict:")
print(stock)

Series from list:
0    22
1    25
2    19
3    30
4    28
dtype: int64

Series with labels:
Mon    22
Tue    25
Wed    19
Thu    30
Fri    28
dtype: int64

Series from dict:
AAPL     150.2
GOOG    2800.5
MSFT     299.0
dtype: float64

In [ ]:
#Elemets using the name of the element itsef
temps_labelled = pd.Series([22, 25, 19, 30, 28], index=['Mon', 'Tue', 'Wed', 'Thu', 'Fri'])
print(temps_labelled)

print(temps_labelled.loc["Wed"])

Mon    22
Tue    25
Wed    19
Thu    30
Fri    28
dtype: int64
19

In [11]:
#elements using the position/ index
print(temps_labelled.iloc[2])

19

In [ ]:
temps_labelled = pd.Series([22, 25, 19, 30, 28], index=['Mon', 'Tue', 'Wed', 'Thu', 'Fri'])
print(temps_labelled)

temps_by_9 = temps_labelled * 9 
print(temps_by_9)

Mon    22
Tue    25
Wed    19
Thu    30
Fri    28
dtype: int64
Mon    198
Tue    225
Wed    171
Thu    270
Fri    252
dtype: int64

In [24]:
#Useful methods/ functions in pandas
cities = pd.Series(['Cape Town', 'Johannesburg', 'Cape Town', 'Durban', 'johannesburg', 'Cape Town', 'Joburg'])
#print(cities)

print(cities.unique())

#print(cities.nunique())
cities.value_counts()

<StringArray>
['Cape Town', 'Johannesburg', 'Durban', 'johannesburg', 'Joburg']
Length: 5, dtype: str

Cape Town       3
Johannesburg    1
Durban          1
johannesburg    1
Joburg          1
Name: count, dtype: int64

In [ ]:
# Accessing elements
print("By label  (loc): ", temps_labelled.loc['Wed'])   # 19 — label-based
print("By position (iloc):", temps_labelled.iloc[2])    # 19 — position-based

# Vectorized operations — just like NumPy!
print("\nTemp in Fahrenheit:", temps_labelled * 9/5 + 32)

# Useful Series methods
cities = pd.Series(['Cape Town', 'Johannesburg', 'Cape Town', 'Durban', 'Johannesburg', 'Cape Town'])
print("\nValue counts (frequency):")
print(cities.value_counts())
print("\nUnique values:", cities.unique())
print("Number of unique:", cities.nunique())

## 4.8 — Loading Data into a DataFrame

In practice, you'll almost always load data from a file rather than typing it in manually.

In [36]:
cols = ["first_col", "second_col", "target"]
df = pd.read_csv("Percept1.csv", sep=";", header=None, names=cols, usecols=["second_col", "target"], nrows=10) 

df.head()  #first 5 rows of your data

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   second_col  10 non-null     float64
 1   target      10 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 292.0 bytes

In [67]:
# --- Loading from a CSV (most common) ---
# df = pd.read_csv('your_file.csv') 

# Key parameters you'll use constantly:
# sep=','           → delimiter (use sep='\t' for tab-separated)
# header=0          → row to use as column names (default is row 0)
# index_col='id'    → use a specific column as the row index
# usecols=['a','b'] → load only specific columns (saves memory)
# dtype={'age':int} → specify data types upfront
# na_values=['N/A'] → treat these strings as missing values
# skiprows=2        → skip the first 2 rows
# nrows=1000        → load only the first 1000 rows (for testing)
# encoding='utf-8'  → file encoding (try 'latin-1' if utf-8 fails)

# --- Loading from a URL ---
# df = pd.read_csv('https://raw.githubusercontent.com/.../data.csv')

# --- Loading from Excel ---
# df = pd.read_excel('file.xlsx', sheet_name='Sheet1')

# --- Loading from JSON ---
# df = pd.read_json('file.json')

# --- Creating from Python data structures ---
# From a list of dicts (most natural)
data = [
    {'name': 'Alice',   'age': 28, 'city': 'Cape Town',    'salary': 52000, 'dept': 'Engineering'},
    {'name': 'Bob',     'age': 34, 'city': 'Johannesburg', 'salary': 68000, 'dept': 'Marketing'},
    {'name': 'Carol',   'age': 29, 'city': 'Durban',       'salary': 45000, 'dept': 'Engineering'},
    {'name': 'David',   'age': 45, 'city': 'Cape Town',    'salary': 91000, 'dept': 'Management'},
    {'name': 'Eve',     'age': 31, 'city': 'Johannesburg', 'salary': 61000, 'dept': 'Marketing'},
    {'name': 'Frank',   'age': 52, 'city': 'Pretoria',     'salary': 75000, 'dept': 'Management'},
    {'name': 'Grace',   'age': 27, 'city': 'Durban',       'salary': 41000, 'dept': 'Engineering'},
    {'name': 'Henry',   'age': 38, 'city': 'Cape Town',    'salary': 58000, 'dept': 'Marketing'},
    {'name': 'Iris',    'age': 33, 'city': 'Johannesburg', 'salary': None,  'dept': 'Engineering'},
    {'name': 'Jack',    'age': None,'city': 'Cape Town',   'salary': 83000, 'dept': 'Management'},
    {'name': 'Jack',    'age': None,'city': 'Cape Town',   'salary': 83000, 'dept': 'Management'}
]
df = pd.DataFrame(data)
print("DataFrame created!")
df

DataFrame created!

     name   age          city   salary         dept
0   Alice  28.0     Cape Town  52000.0  Engineering
1     Bob  34.0  Johannesburg  68000.0    Marketing
2   Carol  29.0        Durban  45000.0  Engineering
3   David  45.0     Cape Town  91000.0   Management
4     Eve  31.0  Johannesburg  61000.0    Marketing
5   Frank  52.0      Pretoria  75000.0   Management
6   Grace  27.0        Durban  41000.0  Engineering
7   Henry  38.0     Cape Town  58000.0    Marketing
8    Iris  33.0  Johannesburg      NaN  Engineering
9    Jack   NaN     Cape Town  83000.0   Management
10   Jack   NaN     Cape Town  83000.0   Management

## 4.9 — The Standard EDA Opening Sequence

Every time you encounter a new dataset, run through this sequence **before doing anything else**.

Memorise this — it's the professional data scientist's first move.

In [40]:
# STEP 1: Scale of the problem
print("Shape (rows, cols):", df.shape)

Shape (rows, cols): (10, 5)

In [41]:
# STEP 2: Data types — are numbers stored as numbers? Are dates stored as dates?
print(df.dtypes)

name          str
age       float64
city          str
salary    float64
dept          str
dtype: object

In [44]:
# STEP 3: First and last rows
df.head()   # First 5 rows

    name   age          city   salary         dept
0  Alice  28.0     Cape Town  52000.0  Engineering
1    Bob  34.0  Johannesburg  68000.0    Marketing
2  Carol  29.0        Durban  45000.0  Engineering
3  David  45.0     Cape Town  91000.0   Management
4    Eve  31.0  Johannesburg  61000.0    Marketing

In [45]:
df.tail()   # Last 3 rows

    name   age          city   salary         dept
5  Frank  52.0      Pretoria  75000.0   Management
6  Grace  27.0        Durban  41000.0  Engineering
7  Henry  38.0     Cape Town  58000.0    Marketing
8   Iris  33.0  Johannesburg      NaN  Engineering
9   Jack   NaN     Cape Town  83000.0   Management

In [49]:
# STEP 4: Random sample — avoids head/tail bias!
# (Important: head() might show a tidy "top" of the data that's not representative)
df.sample(5, random_state=42)

    name   age          city   salary         dept
8   Iris  33.0  Johannesburg      NaN  Engineering
1    Bob  34.0  Johannesburg  68000.0    Marketing
5  Frank  52.0      Pretoria  75000.0   Management
0  Alice  28.0     Cape Town  52000.0  Engineering
7  Henry  38.0     Cape Town  58000.0    Marketing

In [55]:
# STEP 5: Comprehensive overview — non-null counts, dtypes, memory
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    10 non-null     str
 1   age     9 non-null      float64
 2   city    10 non-null     str
 3   salary  9 non-null      float64
 4   dept    10 non-null     str
dtypes: float64(2), str(3)
memory usage: 532.0 bytes

In [54]:
# STEP 6: Summary statistics for numeric columns int, float
df.describe()

             age        salary
count   9.000000      9.000000
mean   35.222222  63777.777778
std     8.422853  16976.290656
min    27.000000  41000.000000
25%    29.000000  52000.000000
50%    33.000000  61000.000000
75%    38.000000  75000.000000
max    52.000000  91000.000000

In [58]:
# STEP 7: Summary statistics for string/object columns
df.describe(include='all')

         name        age       city        salary         dept
count      10   9.000000         10      9.000000           10
unique     10        NaN          4           NaN            3
top     Alice        NaN  Cape Town           NaN  Engineering
freq        1        NaN          4           NaN            4
mean      NaN  35.222222        NaN  63777.777778          NaN
std       NaN   8.422853        NaN  16976.290656          NaN
min       NaN  27.000000        NaN  41000.000000          NaN
25%       NaN  29.000000        NaN  52000.000000          NaN
50%       NaN  33.000000        NaN  61000.000000          NaN
75%       NaN  38.000000        NaN  75000.000000          NaN
max       NaN  52.000000        NaN  91000.000000          NaN

In [64]:
df.isnull().mean()  # if its less than 5% you can safely drop them, impute missing values; subtitute them with mean, median or mode

name      0.0
age       0.1
city      0.0
salary    0.1
dept      0.0
dtype: float64

In [65]:
# STEP 8: Missing values — count and rate
print("Missing value COUNT per column:")
print(df.isnull().sum())
print()
print("Missing value RATE per column (more useful as % of total rows):")
print((df.isnull().mean() * 100).round(1).astype(str) + '%')

Missing value COUNT per column:
name      0
age       1
city      0
salary    1
dept      0
dtype: int64

Missing value RATE per column (more useful as % of total rows):
name       0.0%
age       10.0%
city       0.0%
salary    10.0%
dept       0.0%
dtype: str

In [69]:
df.duplicated().sum()

np.int64(1)

In [73]:
cols = df.columns.tolist()
print(cols)

['name', 'age', 'city', 'salary', 'dept']

In [ ]:
# STEP 9: Duplicate rows
print("Number of exact duplicate rows:", df.duplicated().sum())

# STEP 10: Column names
print("Column names:", df.columns.tolist())

## 🏋️ Week 4 Exercises

Try these yourself before looking at the solutions!

**Exercise 1:** Create a NumPy array of 20 evenly-spaced values between 0 and 100 (inclusive). What is the mean? What is the standard deviation?

**Exercise 2:** Create a 4×5 NumPy array of random integers between 10 and 50. Then:
- Print its shape, number of dimensions, and total size.
- Find the maximum value in each row.
- Find the minimum value in each column.

**Exercise 3:** Using the `df` DataFrame created above:
- Run the full EDA opening sequence.
- Answer: How many missing values are there? Which columns have them?

In [ ]:
# Exercise 1: Your solution here

In [ ]:
# Exercise 2: Your solution here

In [ ]:
# Exercise 3: Your solution here

---
# 🔍 WEEK 5: Selecting, Filtering, and Cleaning Data
---

First, let's create a richer dataset to work with throughout this week.

In [ ]:
import pandas as pd
import numpy as np

np.random.seed(42)

# A realistic employee dataset with common real-world issues
employees = pd.DataFrame({
    'emp_id':     [f'E{str(i).zfill(3)}' for i in range(1, 21)],
    'name':       ['Alice Johnson', 'Bob Smith', 'Carol White', 'David Brown', 'Eve Davis',
                   'Frank Miller', 'Grace Wilson', 'Henry Moore', 'Iris Taylor', 'Jack Anderson',
                   'Karen Thomas', 'Liam Jackson', 'Mia Harris', 'Noah Martin', 'Olivia Garcia',
                   'Peter Martinez', 'Quinn Robinson', 'Rachel Clark', 'Sam Lewis', 'Tina Lee'],
    'department':  ['Engineering','Marketing','Engineering','Management','Marketing',
                    'Management','Engineering','Marketing','Engineering','Management',
                    'HR','Engineering','HR','Marketing','Engineering',
                    'Management','HR','Engineering','Marketing','HR'],
    'city':        ['Cape Town','Johannesburg','Durban','Cape Town','Johannesburg',
                    'Pretoria','Durban','Cape Town','Johannesburg','Cape Town',
                    'Durban','Johannesburg','Cape Town','Pretoria','Durban',
                    'Johannesburg','Cape Town','Durban','Johannesburg','Pretoria'],
    'salary':      [52000,68000,45000,91000,61000,75000,41000,58000,None,83000,
                    47000,63000,None,71000,49000,88000,44000,56000,65000,51000],
    'age':         [28,34,29,45,31,52,27,38,33,None,41,26,36,49,30,55,28,35,43,32],
    'start_date':  ['2020-03-15','2018-07-22','2021-01-10','2015-11-05','2019-06-30',
                    '2013-04-18','2022-02-28','2017-09-14','2020-08-01','2016-12-20',
                    '2021-05-17','2023-01-09','2019-10-25','2014-03-31','2022-07-04',
                    '2012-08-15','2021-11-30','2018-04-22','2017-06-10','2020-09-03'],
    'performance': ['Excellent','Good','Good','Excellent','Average','Good','Average','Good',
                    'Excellent','Excellent','Good','Average','Good','Excellent','Average',
                    'Good','Good','Excellent','Average','Good'],
    'phone':       [' 021-555-1234 ', '011-555-5678', '031-555-9012', ' 021-555-3456', '011-555-7890',
                    '012-555-1111', '031-555-2222', ' 021-555-3333', '011-555-4444', '021-555-5555',
                    '031-555-6666', '011-555-7777', '021-555-8888', '012-555-9999', '031-555-0000',
                    '011-555-1112', '021-555-2223', '031-555-3334', '011-555-4445', '012-555-5556'],
})

# Convert start_date to datetime
employees['start_date'] = pd.to_datetime(employees['start_date'])

print(f"Dataset shape: {employees.shape}")
employees.head()

## 5.1 — Column and Row Selection

Understanding `.loc` vs `.iloc` is fundamental. The difference:
- **`.loc`** = **L**abel-based (use the actual name/label)
- **`.iloc`** = **I**nteger position-based (use 0, 1, 2, ... like list indexing)

In [ ]:
# --- COLUMN SELECTION ---

# Single column → returns a Series
names_series = employees['name']
print("Type:", type(names_series))  # pandas.core.series.Series

# Single column → returns a DataFrame (note the double brackets [[]])
names_df = employees[['name']]
print("Type:", type(names_df))      # pandas.core.frame.DataFrame

# Multiple columns
subset = employees[['name', 'department', 'salary']]
subset.head()

In [ ]:
# --- .loc: LABEL-BASED indexing ---
# Syntax: df.loc[rows, columns]
# 'rows' can be: a label, list of labels, boolean array, or slice
# 'columns' can be: a label, list of labels, or slice

# Select row with index label 0, all columns
print("Row 0:\n", employees.loc[0])
print()

# Select rows 0-4, specific columns
employees.loc[0:4, ['name', 'department', 'salary']]

In [ ]:
# --- .iloc: POSITION-BASED indexing ---
# Syntax: df.iloc[row_positions, col_positions]
# Use integers, just like Python list slicing
# Note: slices EXCLUDE the end, unlike .loc which INCLUDES it!

# First 3 rows, first 4 columns
employees.iloc[0:3, 0:4]

In [ ]:
# Last 3 rows, last 3 columns (negative indexing works!)
employees.iloc[-3:, -3:]

In [ ]:
# Setting values correctly — ALWAYS use .loc to avoid warnings
# Find employees with missing salary and note their indices
print("Missing salary indices:", employees[employees['salary'].isnull()].index.tolist())

# Correct way to set a value
# employees.loc[employees['salary'].isnull(), 'salary'] = employees['salary'].median()
# (We'll do this properly in 5.4)

## 5.2 — Boolean Filtering

One of the most-used skills in data analysis. Think of it as asking questions about your data.

⚠️ **Critical rule:** Use `&` (AND), `|` (OR), `~` (NOT) — NOT Python's `and`, `or`, `not`!  
⚠️ **Critical rule:** Wrap each condition in parentheses `()` when combining!

In [ ]:
# Single condition
senior_staff = employees[employees['age'] > 40]
print(f"Employees over 40: {len(senior_staff)}")
senior_staff[['name', 'age', 'department']]

In [ ]:
# Multiple conditions with & (AND)
# Find Cape Town Engineering employees
ct_engineering = employees[
    (employees['city'] == 'Cape Town') &
    (employees['department'] == 'Engineering')
]
print("Cape Town Engineering employees:")
ct_engineering[['name', 'city', 'department', 'salary']]

In [ ]:
# | (OR) condition
management_or_hr = employees[
    (employees['department'] == 'Management') |
    (employees['department'] == 'HR')
]
print(f"Management or HR: {len(management_or_hr)} employees")

# Better way to do OR across many values: .isin()
management_or_hr_v2 = employees[employees['department'].isin(['Management', 'HR'])]
print(f"Using .isin(): {len(management_or_hr_v2)} employees")  # Same result!

In [ ]:
# ~ (NOT) condition
not_marketing = employees[~(employees['department'] == 'Marketing')]
print(f"Non-marketing departments: {not_marketing['department'].unique()}")

# NOT IN pattern
not_cape_town_jozi = employees[~employees['city'].isin(['Cape Town', 'Johannesburg'])]
print(f"\nEmployees NOT in Cape Town or Johannesburg:")
print(not_cape_town_jozi[['name', 'city']].values)

In [ ]:
# .between() for range filtering
mid_salary = employees[employees['salary'].between(50000, 70000)]
print(f"Employees earning R50k-R70k: {len(mid_salary)}")

# .query() — string-based filtering (cleaner for complex queries)
# Variables from the environment can be referenced with @
min_salary = 60000
query_result = employees.query("salary > @min_salary and department == 'Engineering'")
print(f"\nEngineers earning > R60k:")
query_result[['name', 'salary', 'department']]

## 5.3 — Selecting Columns by Data Type

In [ ]:
# Select only numeric columns
numeric_cols = employees.select_dtypes(include=['number'])
print("Numeric columns:", numeric_cols.columns.tolist())
print(numeric_cols.describe())

# Select only string/categorical columns
text_cols = employees.select_dtypes(include=['object'])
print("\nText columns:", text_cols.columns.tolist())

# Why this is useful: apply the same operation to all numeric columns at once
# e.g. fill all numeric NaN values with 0:
# df[numeric_cols.columns] = df[numeric_cols.columns].fillna(0)

## 5.4 — Handling Missing Data

Missing data is unavoidable. There are three main strategies:

1. **Drop** — remove rows or columns with missing values (only if you can afford to lose data)
2. **Fill (Impute)** — replace missing values with a sensible estimate
3. **Flag** — create a new binary column indicating which rows had missing data, then fill

**Theoretical note:** Missing data has three types:
- **MCAR** (Missing Completely At Random) — no pattern; safe to drop
- **MAR** (Missing At Random) — missingness depends on other observed variables; impute carefully
- **MNAR** (Missing Not At Random) — missingness depends on the missing value itself; most problematic

In [ ]:
# Detecting missing values
print("Missing value summary:")
missing_summary = pd.DataFrame({
    'Count':   employees.isnull().sum(),
    'Rate (%)': (employees.isnull().mean() * 100).round(1)
})
print(missing_summary[missing_summary['Count'] > 0])

In [ ]:
# DROPPING
print(f"Original rows: {len(employees)}")

# Drop rows where ANY column is null
dropped_any = employees.dropna()
print(f"After dropna() (any):  {len(dropped_any)}")

# Drop rows where ALL columns are null (almost never happens)
dropped_all = employees.dropna(how='all')
print(f"After dropna() (all):  {len(dropped_all)}")

# Drop rows only if they're missing in SPECIFIC columns
dropped_salary = employees.dropna(subset=['salary'])
print(f"After dropna(subset=['salary']): {len(dropped_salary)}")

# Drop COLUMNS where more than 50% of values are missing
thresh_rows = int(0.5 * len(employees))
dropped_cols = employees.dropna(axis=1, thresh=thresh_rows)
print(f"\nColumns after 50% threshold: {dropped_cols.columns.tolist()}")

In [ ]:
# FILLING (Imputation)
# Work on a copy so we don't modify the original
emp_clean = employees.copy()

# BEFORE: count missing values
print("Before filling:")
print(emp_clean[['salary', 'age']].isnull().sum())

# Fill numeric with median (robust to outliers — better than mean)
salary_median = emp_clean['salary'].median()
emp_clean['salary'] = emp_clean['salary'].fillna(salary_median)
print(f"\nFilled missing salary with median: R{salary_median:,.0f}")

# Fill numeric with mean (only if distribution is roughly symmetric)
age_mean = emp_clean['age'].mean()
emp_clean['age'] = emp_clean['age'].fillna(round(age_mean))
print(f"Filled missing age with mean: {round(age_mean)}")

# AFTER: verify
print("\nAfter filling:")
print(emp_clean[['salary', 'age']].isnull().sum())

In [ ]:
# FLAGGING — create a binary indicator BEFORE filling
# This preserves information about which rows were imputed
emp_flagged = employees.copy()

# Create flag columns (1 = was missing, 0 = was present)
emp_flagged['salary_was_missing'] = emp_flagged['salary'].isnull().astype(int)
emp_flagged['age_was_missing']    = emp_flagged['age'].isnull().astype(int)

# Then fill
emp_flagged['salary'] = emp_flagged['salary'].fillna(emp_flagged['salary'].median())
emp_flagged['age']    = emp_flagged['age'].fillna(emp_flagged['age'].mean())

# Check which rows were flagged
flagged_rows = emp_flagged[(emp_flagged['salary_was_missing'] == 1) | (emp_flagged['age_was_missing'] == 1)]
print("Rows that had missing values:")
flagged_rows[['name', 'salary', 'salary_was_missing', 'age', 'age_was_missing']]

## 5.5 — Creating, Renaming, and Dropping Columns

In [ ]:
# We'll use our clean copy
emp = emp_clean.copy()

# --- CREATING NEW COLUMNS ---

# Simple arithmetic
emp['annual_bonus'] = emp['salary'] * 0.10
print("Added bonus column.")

# Using np.where (vectorized if/else) — much faster than apply+lambda
emp['is_senior'] = np.where(emp['age'] >= 40, 'Senior', 'Junior')

# Complex conditional: categorise salary bands
emp['salary_band'] = np.select(
    condlist=[
        emp['salary'] < 50000,
        emp['salary'] < 70000,
        emp['salary'] < 90000
    ],
    choicelist=['Low', 'Mid', 'High'],
    default='Executive'
)

emp[['name', 'salary', 'annual_bonus', 'is_senior', 'salary_band']].head(8)

In [ ]:
# df.assign() — great for method chaining (creates a new DataFrame, doesn't modify original)
emp2 = (
    emp
    .assign(total_comp = lambda x: x['salary'] + x['annual_bonus'])
    .assign(name_upper = lambda x: x['name'].str.upper())
)
emp2[['name', 'name_upper', 'salary', 'annual_bonus', 'total_comp']].head(3)

In [ ]:
# --- RENAMING COLUMNS ---
emp = emp.rename(columns={'emp_id': 'employee_id', 'dept': 'department'})
print("Renamed emp_id to employee_id")

# Rename ALL columns at once — standardize to lowercase with underscores
# (Good practice for consistent, code-friendly column names)
emp.columns = [col.lower().strip().replace(' ', '_') for col in emp.columns]
print("All column names:", emp.columns.tolist())

# --- DROPPING COLUMNS ---
emp = emp.drop(columns=['annual_bonus'])  # Drop one
print("\nDropped 'annual_bonus'")

# --- REORDERING COLUMNS ---
# Move the most important columns to the front
important_first = ['employee_id', 'name', 'department', 'city', 'salary', 'age']
other_cols = [c for c in emp.columns if c not in important_first]
emp = emp[important_first + other_cols]
emp.head(3)

## 5.6 — Data Type Conversion

Incorrect data types cause silent errors — a number stored as a string won't be averaged correctly.

In [ ]:
# Demonstrate the danger of wrong dtypes
bad_data = pd.Series(['35', '42', '28', 'N/A', '55'])
print("Dtype:", bad_data.dtype)  # object (string!)
# bad_data.mean()  # This would raise a TypeError!

# pd.to_numeric with errors='coerce' — converts bad values to NaN instead of crashing
good_data = pd.to_numeric(bad_data, errors='coerce')
print("After to_numeric:", good_data.values)
print("Mean:", good_data.mean())

# Convert to categorical (for memory efficiency and proper ordering)
emp['department'] = emp['department'].astype('category')
emp['performance'] = pd.Categorical(
    emp['performance'],
    categories=['Average', 'Good', 'Excellent'],
    ordered=True  # Now 'Excellent' > 'Good' > 'Average'
)
print("\nPerformance as ordered category:")
print(emp['performance'].value_counts())
print("Is 'Excellent' > 'Good'?", 'Excellent' > 'Good')  # Can now compare!

In [ ]:
# Converting strings to datetime
# Check current dtype
print("start_date dtype:", emp['start_date'].dtype)

# If it were a string, we'd do:
# emp['start_date'] = pd.to_datetime(emp['start_date'], format='%Y-%m-%d')
# Note: specifying format is much faster than letting Pandas infer it
print("Sample start_date values:")
print(emp['start_date'].head())

## 5.7 — Handling Duplicates

In [ ]:
# Create a dataset with duplicates
dupes_df = pd.DataFrame({
    'id':   [1, 2, 3, 2, 4, 1],
    'name': ['Alice', 'Bob', 'Carol', 'Bob', 'David', 'Alice'],
    'city': ['CPT', 'JHB', 'DBN', 'JHB', 'PTA', 'CPT']
})

print("Original DataFrame:")
print(dupes_df)

# Detect duplicates
print(f"\nExact duplicate rows: {dupes_df.duplicated().sum()}")
print("Which rows are duplicates?")
print(dupes_df[dupes_df.duplicated(keep=False)])  # keep=False shows ALL copies

# Detect duplicates based on specific columns (partial key)
print(f"\nDuplicate id values: {dupes_df.duplicated(subset=['id']).sum()}")

# Drop duplicates
deduped = dupes_df.drop_duplicates()                         # keep='first' (default)
deduped_last = dupes_df.drop_duplicates(keep='last')          # keep the last occurrence
deduped_none = dupes_df.drop_duplicates(keep=False)           # remove ALL copies
print(f"\nKeep first: {len(deduped)} rows | Keep last: {len(deduped_last)} | Keep none: {len(deduped_none)}")

## 5.8 — String Operations with the `.str` Accessor

The `.str` accessor gives you string methods that work on every element in a Series.

In [ ]:
# Let's clean up the phone number column
print("Raw phone values:")
print(emp['phone'].head())

# Remove leading/trailing whitespace
emp['phone'] = emp['phone'].str.strip()
print("\nAfter strip():")
print(emp['phone'].head())

In [ ]:
# Common string operations
names = emp['name'].copy()

print("Uppercase:     ", names.str.upper().head(3).values)
print("Lowercase:     ", names.str.lower().head(3).values)
print("Length:        ", names.str.len().head(3).values)
print("Contains 'son':", names.str.contains('son', na=False).head(5).values)
print("Starts with 'A':", names.str.startswith('A').values)

# Split into first and last name — expand=True creates separate columns
name_split = names.str.split(' ', expand=True)
name_split.columns = ['first_name', 'last_name']
print("\nSplit into first/last:")
name_split.head(5)

In [ ]:
# Extract information using regex
# Extract the area code from phone numbers (first 3 digits)
emp['area_code'] = emp['phone'].str.extract(r'^(\d{3})')
print("Area codes:")
print(emp[['phone', 'area_code']].head())

# Replace — normalize spelling variations
messy_cities = pd.Series(['Cape Town', 'cape town', 'CAPE TOWN', 'Capetown', 'Cape-Town'])
cleaned = messy_cities.str.lower().str.replace(r'[-]', ' ', regex=True).str.title()
print("\nCleaned cities:")
print(cleaned.values)

## 5.9 — Datetime Operations with the `.dt` Accessor

In [ ]:
# The .dt accessor extracts components from datetime columns
dates = emp['start_date']

print("Year:     ", dates.dt.year.values)
print("Month:    ", dates.dt.month.values)
print("Day:      ", dates.dt.day.values[:5])
print("Day name: ", dates.dt.day_name().values[:5])
print("Day of week:", dates.dt.dayofweek.values[:5])  # 0=Monday, 6=Sunday
print("Quarter:  ", dates.dt.quarter.values)

In [ ]:
# Calculate tenure (days/years employed)
today = pd.Timestamp('2026-06-09')  # Fixed date for reproducibility
emp['tenure_days'] = (today - emp['start_date']).dt.days
emp['tenure_years'] = (emp['tenure_days'] / 365.25).round(1)

print("Tenure summary:")
emp[['name', 'start_date', 'tenure_days', 'tenure_years']].sort_values('tenure_years', ascending=False).head(5)

In [ ]:
# Generate date sequences — useful for time series analysis
date_range = pd.date_range(start='2024-01-01', periods=12, freq='MS')  # MS = Month Start
print("Monthly date range (2024):")
print(date_range)

# Filter rows by date
recent_hires = emp[emp['start_date'] >= '2021-01-01']
print(f"\nEmployees hired from 2021 onwards: {len(recent_hires)}")

## 🏋️ Week 5 Exercises

**Exercise 1:** Using the `employees` DataFrame:
- Find all employees who earn more than R60,000 AND work in either Engineering OR Management.
- How many are there? List their names and salaries.

**Exercise 2:** Clean and enrich the data:
- Fill missing salaries with the **department median** salary (not the overall median).
- Create a new column `full_tenure` as a string like `"3 years, 2 months"`.

**Exercise 3:** Extract from the `name` column:
- Create separate `first_name` and `last_name` columns.
- Create an `email` column in the format `firstname.lastname@company.com` (all lowercase).

In [ ]:
# Exercise 1

In [ ]:
# Exercise 2

In [ ]:
# Exercise 3

---
# 🔗 WEEK 6: Grouping, Reshaping, and Merging
---

Setup — use the clean employee data and add sales data.

In [ ]:
import pandas as pd
import numpy as np

np.random.seed(42)

# Employee data (clean version)
employees = pd.DataFrame({
    'emp_id':     [f'E{str(i).zfill(3)}' for i in range(1, 16)],
    'name':       ['Alice J', 'Bob S', 'Carol W', 'David B', 'Eve D',
                   'Frank M', 'Grace W', 'Henry M', 'Iris T', 'Jack A',
                   'Karen T', 'Liam J', 'Mia H', 'Noah M', 'Olivia G'],
    'department':  ['Engineering','Marketing','Engineering','Management','Marketing',
                    'Management','Engineering','Marketing','Engineering','Management',
                    'HR','Engineering','HR','Marketing','Engineering'],
    'city':        ['Cape Town','Johannesburg','Durban','Cape Town','Johannesburg',
                    'Pretoria','Durban','Cape Town','Johannesburg','Cape Town',
                    'Durban','Johannesburg','Cape Town','Pretoria','Durban'],
    'salary':      [52000,68000,45000,91000,61000,75000,41000,58000,63000,83000,
                    47000,63000,44000,71000,49000],
    'age':         [28,34,29,45,31,52,27,38,33,47,41,26,36,49,30],
    'start_date':  pd.to_datetime(['2020-03-15','2018-07-22','2021-01-10','2015-11-05','2019-06-30',
                    '2013-04-18','2022-02-28','2017-09-14','2020-08-01','2016-12-20',
                    '2021-05-17','2023-01-09','2019-10-25','2014-03-31','2022-07-04']),
    'performance': ['Excellent','Good','Good','Excellent','Average','Good','Average','Good',
                    'Excellent','Excellent','Good','Average','Good','Excellent','Average'],
})

# Monthly sales data for employees
months = ['Jan','Feb','Mar','Apr','May','Jun']
sales_wide = pd.DataFrame({
    'emp_id': [f'E{str(i).zfill(3)}' for i in range(1, 11)],
    'Jan': np.random.randint(10000, 80000, 10),
    'Feb': np.random.randint(10000, 80000, 10),
    'Mar': np.random.randint(10000, 80000, 10),
    'Apr': np.random.randint(10000, 80000, 10),
    'May': np.random.randint(10000, 80000, 10),
    'Jun': np.random.randint(10000, 80000, 10),
})

# Department info table (separate table)
dept_info = pd.DataFrame({
    'department': ['Engineering', 'Marketing', 'Management', 'HR'],
    'dept_head': ['Sarah K', 'Tom R', 'Linda P', 'James F'],
    'budget_m':  [5.2, 3.1, 2.8, 1.5],  # Budget in millions
    'floor':     [3, 2, 5, 1]
})

print("employees:", employees.shape)
print("sales_wide:", sales_wide.shape)
print("dept_info:", dept_info.shape)
employees.head()

## 6.1 — Sorting

In [ ]:
# Sort by a single column
by_salary = employees.sort_values('salary', ascending=False)
print("Top 5 earners:")
print(by_salary[['name', 'department', 'salary']].head())

# Multi-column sort
# Sort by department (A-Z), then by salary (high to low) within each department
multi_sort = employees.sort_values(
    by=['department', 'salary'],
    ascending=[True, False]
)
print("\nSorted by dept then salary:")
print(multi_sort[['name', 'department', 'salary']].head(8))

# Quick way to get top/bottom N
print("\nTop 3 salaries:")
print(employees.nlargest(3, 'salary')[['name', 'salary']].values)

## 6.2 — GroupBy Operations

The **split-apply-combine** paradigm is the foundation of GroupBy:

1. **Split** the DataFrame into groups based on some key
2. **Apply** a function to each group independently
3. **Combine** the results back into a single output

```
Full DataFrame → [Group A] [Group B] [Group C]  ← SPLIT
                     ↓          ↓          ↓     ← APPLY (e.g., mean)
                   mean_A    mean_B    mean_C
                     ↓                           ← COMBINE
                 [mean_A, mean_B, mean_C]
```

In [ ]:
# Basic groupby: average salary per department
dept_avg = employees.groupby('department')['salary'].mean().round(0)
print("Average salary by department:")
print(dept_avg.sort_values(ascending=False))

In [ ]:
# Group by multiple columns
city_dept = employees.groupby(['department', 'city'])['salary'].mean().round(0)
print("Average salary by department AND city:")
print(city_dept)

In [ ]:
# .agg() — apply multiple aggregation functions at once
dept_stats = employees.groupby('department').agg(
    headcount     = ('name', 'count'),
    avg_salary    = ('salary', 'mean'),
    min_salary    = ('salary', 'min'),
    max_salary    = ('salary', 'max'),
    total_payroll = ('salary', 'sum'),
    avg_age       = ('age', 'mean')
).round(0)

print("Department statistics:")
dept_stats

In [ ]:
# .transform() — adds group statistics BACK to each row (same shape as original!)
# Great for creating relative metrics
employees['dept_avg_salary'] = employees.groupby('department')['salary'].transform('mean').round(0)
employees['salary_vs_dept_avg'] = ((employees['salary'] - employees['dept_avg_salary']) / employees['dept_avg_salary'] * 100).round(1)

print("Salary vs department average (% difference):")
employees[['name', 'department', 'salary', 'dept_avg_salary', 'salary_vs_dept_avg']].sort_values('salary_vs_dept_avg', ascending=False)

In [ ]:
# .filter() — keep only groups that satisfy a condition
# Keep only departments with more than 2 employees
large_depts = employees.groupby('department').filter(lambda x: len(x) > 2)
print(f"Departments with > 2 employees: {large_depts['department'].unique()}")
print(f"Rows retained: {len(large_depts)} of {len(employees)}")

## 6.3 — Pivot Tables

Pivot tables are one of the most common tools for summarising data — familiar from Excel.

In [ ]:
# Pivot table: average salary by city (rows) and department (columns)
pivot = pd.pivot_table(
    employees,
    values='salary',          # What to aggregate
    index='city',             # Row grouping
    columns='department',     # Column grouping
    aggfunc='mean',           # How to aggregate
    fill_value=0,             # What to put where there's no data
    margins=True,             # Add row/column totals
    margins_name='Total'
).round(0)

print("Average salary by city and department:")
pivot

In [ ]:
# Cross-tabulation — frequency counts between two categorical columns
crosstab = pd.crosstab(
    employees['department'],
    employees['performance'],
    margins=True
)
print("Headcount by department and performance:")
print(crosstab)

# Normalize to see proportions
crosstab_pct = pd.crosstab(
    employees['department'],
    employees['performance'],
    normalize='index'  # As % of each row (department)
).round(2)
print("\nAs % of each department:")
print(crosstab_pct)

## 6.4 — Melting and Reshaping

**Wide format:** each variable has its own column (e.g., `Jan`, `Feb`, `Mar` as separate columns).  
**Long format:** each observation is a row (e.g., `month` and `sales` as two columns).

Most analysis tools prefer **long format**. Many databases store data in long format.

In [ ]:
print("WIDE format (each month = its own column):")
print(sales_wide.head(3))
print(f"Shape: {sales_wide.shape}")

# pd.melt — convert wide to long
sales_long = pd.melt(
    sales_wide,
    id_vars=['emp_id'],           # Columns to keep (identifiers)
    value_vars=['Jan','Feb','Mar','Apr','May','Jun'],  # Columns to 'melt'
    var_name='month',             # Name for the new 'variable' column
    value_name='sales'            # Name for the new 'value' column
)

print("\nLONG format (each row = one employee + one month):")
print(sales_long.head(8))
print(f"Shape: {sales_long.shape}")

In [ ]:
# Long back to wide: df.pivot()
back_to_wide = sales_long.pivot(
    index='emp_id',
    columns='month',
    values='sales'
)
# Clean up column index name
back_to_wide.columns.name = None
back_to_wide = back_to_wide.reset_index()

print("Back to wide format:")
back_to_wide.head(3)

In [ ]:
# stack() and unstack() — useful with MultiIndex DataFrames
# Create a small multi-index example
grouped = employees.groupby(['department', 'city'])['salary'].mean().round(0)
print("Grouped (MultiIndex Series):")
print(grouped.head(8))

# unstack() — innermost index level becomes columns
unstacked = grouped.unstack()
print("\nAfter unstack() — cities become columns:")
print(unstacked)

## 6.5 — Combining DataFrames

Real data lives in multiple tables. Knowing how to combine them is essential.

In [ ]:
# pd.concat — stacking DataFrames with the same columns

# Create two batches of new hires
batch1 = employees[['emp_id','name','department','salary']].head(3)
batch2 = pd.DataFrame({
    'emp_id': ['E016', 'E017'],
    'name': ['Uma P', 'Victor N'],
    'department': ['HR', 'Engineering'],
    'salary': [46000, 55000]
})

# Stack rows (axis=0 is default)
combined = pd.concat([batch1, batch2], axis=0, ignore_index=True)
print("Combined (stacked rows):")
print(combined)

# keys parameter — track origin
labeled = pd.concat([batch1, batch2], keys=['existing', 'new_hires'])
print("\nWith origin labels (MultiIndex):")
print(labeled)

In [ ]:
# pd.merge — joining DataFrames on a shared key column
# This is like SQL JOIN operations

print("employees (left):")
print(employees[['emp_id','name','department']].head(3))
print("\ndept_info (right):")
print(dept_info)

# INNER JOIN — only rows where key exists in BOTH tables
inner = pd.merge(employees, dept_info, on='department', how='inner')
print(f"\nINNER join: {len(inner)} rows")
print(inner[['name', 'department', 'salary', 'dept_head', 'budget_m']].head(5))

In [ ]:
# Visualise the four join types
print("JOIN TYPES — using sample data:")
print()

left_df  = pd.DataFrame({'id': [1, 2, 3, 4], 'val_L': ['a','b','c','d']})
right_df = pd.DataFrame({'id': [2, 3, 5, 6], 'val_R': ['x','y','z','w']})

print("Left table:",  left_df.values.tolist())
print("Right table:", right_df.values.tolist())
print()

for how in ['inner', 'left', 'right', 'outer']:
    result = pd.merge(left_df, right_df, on='id', how=how)
    print(f"{how.upper():8} join → {len(result)} rows: {result.values.tolist()}")

In [ ]:
# Best practices for merging

# 1. Check shape before and after — detect unexpected row gain/loss
before = len(employees)
merged = pd.merge(employees, dept_info, on='department', how='left')
after = len(merged)
print(f"Rows before: {before} | Rows after: {after}")
print(f"Row count {'unchanged ✓' if before == after else f'CHANGED — investigate! ({after-before:+d} rows)'}")

# 2. When column names differ, use left_on / right_on
# e.g. pd.merge(df1, df2, left_on='dept_name', right_on='department')

# 3. Handle overlapping non-key column names with suffixes
# e.g. pd.merge(df1, df2, on='id', suffixes=('_employees', '_dept'))

# 4. Validate the relationship type to catch data quality issues
try:
    validated = pd.merge(employees, dept_info, on='department', how='left', validate='m:1')
    print("Validation passed: many employees → one department ✓")
except Exception as e:
    print(f"Validation failed: {e}")

## 6.6 — Applying Custom Functions

Sometimes built-in methods aren't enough. `.apply()` lets you run any Python function across a Series or DataFrame.

**Performance note:** Vectorized operations are always faster. Use `.apply()` as a last resort.

In [ ]:
# .apply() on a Series (element-wise)
def classify_salary(salary):
    if salary < 50000:
        return 'Below Market'
    elif salary < 75000:
        return 'At Market'
    else:
        return 'Above Market'

employees['market_position'] = employees['salary'].apply(classify_salary)
print("Salary market positions:")
print(employees['market_position'].value_counts())

In [ ]:
# Lambda functions — inline, anonymous functions for simple operations
employees['salary_k'] = employees['salary'].apply(lambda x: f"R{x/1000:.0f}k")
print("Salary formatted:")
print(employees[['name', 'salary', 'salary_k']].head())

# .apply() on a DataFrame (axis=1 = apply function to each ROW)
# Combine name + department into a display string
employees['display_name'] = employees.apply(
    lambda row: f"{row['name']} ({row['department']})",
    axis=1
)
print("\nDisplay names:")
print(employees['display_name'].values)

In [ ]:
# Comparing performance: .apply() vs vectorized
big_df = pd.DataFrame({'salary': np.random.randint(30000, 150000, 100_000)})

print("Vectorized (fast):")
%timeit big_df['salary'] * 1.10

print("\n.apply() (slow):")
%timeit big_df['salary'].apply(lambda x: x * 1.10)

print("\n💡 Vectorized is typically 10-100x faster than .apply() for simple operations.")
print("Use .apply() only when you need complex, custom logic that can't be vectorized.")

## 🏋️ Week 6 Exercises

**Exercise 1:** Using `groupby()` and `agg()`:
- Calculate the headcount, average salary, total payroll, and youngest/oldest employee per city.
- Which city has the highest average salary?

**Exercise 2:** Melt and analyse the sales data:
- Convert `sales_wide` from wide to long format.
- Merge with `employees` to bring in the `department` column.
- Find the total sales by department and month.

**Exercise 3:** Join tables and answer a business question:
- Merge `employees` with `dept_info` to add `dept_head` and `budget_m` to each employee.
- Then find: for each department, what is the salary budget (total salaries) as a **percentage of** the `budget_m` column?
- Which department has the highest salary-to-budget ratio?

In [ ]:
# Exercise 1

In [ ]:
# Exercise 2

In [ ]:
# Exercise 3

---
# ✅ Exercise Solutions
*(Expand to reveal — try solving them yourself first!)*

---
## Week 4 Solutions

In [ ]:
# W4 Exercise 1
arr = np.linspace(0, 100, 20)
print("Array:", arr)
print("Mean:", np.mean(arr))
print("Std: ", np.std(arr).round(2))

In [ ]:
# W4 Exercise 2
np.random.seed(42)
arr = np.random.randint(10, 50, size=(4, 5))
print("Array:\n", arr)
print("Shape:", arr.shape, "| Dims:", arr.ndim, "| Size:", arr.size)
print("Max per row (axis=1):", np.max(arr, axis=1))
print("Min per col (axis=0):", np.min(arr, axis=0))

In [ ]:
# W4 Exercise 3 — EDA opening sequence was demonstrated above in 4.9
# Answer: salary and age each have 1 missing value (10%)
print("Missing values:")
print(df.isnull().sum()[df.isnull().sum() > 0])

## Week 5 Solutions

In [ ]:
# W5 Exercise 1
# Reload clean employees for solutions
emp_sol = pd.DataFrame({
    'name': ['Alice J','Bob S','Carol W','David B','Eve D','Frank M','Grace W','Henry M','Iris T','Jack A'],
    'department': ['Engineering','Marketing','Engineering','Management','Marketing','Management','Engineering','Marketing','Engineering','Management'],
    'salary': [52000,68000,45000,91000,61000,75000,41000,58000,63000,83000],
    'age': [28,34,29,45,31,52,27,38,33,47]
})

result = emp_sol[
    (emp_sol['salary'] > 60000) &
    (emp_sol['department'].isin(['Engineering', 'Management']))
]
print(f"Count: {len(result)}")
print(result[['name', 'salary', 'department']].to_string(index=False))

In [ ]:
# W5 Exercise 3
emp_sol2 = emp_sol.copy()
emp_sol2['first_name'] = emp_sol2['name'].str.split(' ').str[0]
emp_sol2['last_name']  = emp_sol2['name'].str.split(' ').str[1]
emp_sol2['email']      = (emp_sol2['first_name'] + '.' + emp_sol2['last_name']).str.lower() + '@company.com'
print(emp_sol2[['name', 'first_name', 'last_name', 'email']])

## Week 6 Solutions

In [ ]:
# W6 Exercise 1
city_stats = employees.groupby('city').agg(
    headcount     = ('name', 'count'),
    avg_salary    = ('salary', 'mean'),
    total_payroll = ('salary', 'sum'),
    youngest      = ('age', 'min'),
    oldest        = ('age', 'max')
).round(0).sort_values('avg_salary', ascending=False)

print(city_stats)
print(f"\nHighest avg salary: {city_stats['avg_salary'].idxmax()}")

In [ ]:
# W6 Exercise 3
merged_sol = pd.merge(employees, dept_info, on='department', how='left')

budget_analysis = merged_sol.groupby('department').agg(
    total_salaries = ('salary', 'sum'),
    budget_m = ('budget_m', 'first')
)
budget_analysis['salary_to_budget_pct'] = (
    (budget_analysis['total_salaries'] / (budget_analysis['budget_m'] * 1_000_000)) * 100
).round(1)

print(budget_analysis.sort_values('salary_to_budget_pct', ascending=False))
print(f"\nHighest salary-to-budget: {budget_analysis['salary_to_budget_pct'].idxmax()}")

---
# 📚 Quick Reference Cheat Sheet

## NumPy
| Operation | Code |
|-----------|------|
| Create array | `np.array([1,2,3])` |
| Zeros / Ones | `np.zeros(n)` / `np.ones(n)` |
| Range | `np.arange(start, stop, step)` |
| Evenly spaced | `np.linspace(start, stop, num)` |
| Random seed | `np.random.seed(42)` |
| Shape / Size | `.shape` / `.size` |
| Reshape | `.reshape(rows, cols)` |
| Boolean mask | `arr[arr > 5]` |
| Vectorized if/else | `np.where(cond, x, y)` |
| Axis operations | `np.sum(arr, axis=0)` |

## Pandas — EDA Opening Sequence
```python
df.shape
df.dtypes
df.head(10)
df.sample(5)
df.info()
df.describe()
df.isnull().sum()
df.isnull().mean()
df.duplicated().sum()
```

## Pandas — Selection
| Operation | Code |
|-----------|------|
| Single column (Series) | `df['col']` |
| Single column (DataFrame) | `df[['col']]` |
| Multiple columns | `df[['a','b','c']]` |
| By label | `df.loc[rows, cols]` |
| By position | `df.iloc[rows, cols]` |

## Pandas — Filtering
| Operation | Code |
|-----------|------|
| Basic filter | `df[df['a'] > 10]` |
| AND | `df[(df['a']>10) & (df['b']=='x')]` |
| OR | `df[(df['a']>10) \| (df['b']=='x')]` |
| NOT | `df[~(df['a']>10)]` |
| In list | `df[df['a'].isin(['x','y'])]` |
| Range | `df[df['a'].between(5,10)]` |
| String query | `df.query("a > 10 and b == 'x'")` |

## Pandas — Missing Data
| Operation | Code |
|-----------|------|
| Count missing | `df.isnull().sum()` |
| Drop rows | `df.dropna(subset=['col'])` |
| Fill with value | `df['col'].fillna(0)` |
| Fill with median | `df['col'].fillna(df['col'].median())` |
| Flag missing | `df['flag'] = df['col'].isnull().astype(int)` |

## Pandas — GroupBy
```python
# Basic
df.groupby('col')['target'].mean()

# Multiple aggregations
df.groupby('col').agg(count=('x','count'), avg=('x','mean'))

# Add group stat back to each row
df['group_mean'] = df.groupby('col')['x'].transform('mean')
```

## Pandas — Merging
```python
pd.concat([df1, df2], axis=0, ignore_index=True)  # Stack rows
pd.merge(df_left, df_right, on='key', how='inner')  # SQL-style join
# how options: 'inner', 'left', 'right', 'outer'
```

---

## 🎯 Key Rules to Remember

1. **Always set a random seed** before any random operations: `np.random.seed(42)`
2. **Always run the EDA opening sequence** before any analysis
3. **Use `&`, `|`, `~`** for boolean conditions (NOT `and`, `or`, `not`)
4. **Wrap each condition in parentheses** when combining: `(cond1) & (cond2)`
5. **Use `.loc` to set values**: `df.loc[condition, 'col'] = value`
6. **Use median (not mean)** for imputation when data may have outliers
7. **Flag before you fill** missing values to preserve information
8. **Check `.shape` before and after merging** to detect unexpected row changes
9. **Vectorized operations >> `.apply()`** for performance
10. **Long format is usually better** than wide for analysis and visualization

---

*Module 2 Complete — Next up: Module 3: Data Visualisation with Matplotlib & Seaborn* 📈